# Generated by Django 5.1.2 on 2024-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_uniqueproductnophoto_uniquedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquedetail',
            name='products',
        ),
        migrations.AddField(
            model_name='uniquedetail',
            name='products',
            field=models.ManyToManyField(blank=True, to='services.uniqueproductnophoto'),
        ),
    ]
