# Generated by Django 5.1.2 on 2024-11-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_uniquedetail_products_uniquedetail_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquedetail',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
