# Generated by Django 5.1.2 on 2024-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_truckdisk_truckdisksupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='disksupplier',
            name='price_rozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mototiresupplier',
            name='price_rozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialtiresupplier',
            name='price_rozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tiresupplier',
            name='price_rozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckdisksupplier',
            name='price_rozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trucktiresupplier',
            name='price_rozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
