# Generated by Django 5.1.2 on 2024-11-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_promo_photo_alter_company_protector_avito'),
        ('suppliers', '0003_disksupplier_price_rozn_mototiresupplier_price_rozn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='find_images_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='find_images_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DiskCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_images', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.disk')),
            ],
        ),
        migrations.CreateModel(
            name='TireCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_images', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.tire')),
            ],
        ),
    ]
