# Generated by Django 5.1.2 on 2024-11-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_company_protector_and_more'),
        ('suppliers', '0004_disk_find_images_title_tire_find_images_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mototire',
            name='find_images_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialtire',
            name='find_images_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckdisk',
            name='find_images_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trucktire',
            name='find_images_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MotoTireCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_images', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.disk')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTireCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_images', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.disk')),
            ],
        ),
        migrations.CreateModel(
            name='TruckDiskCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_images', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.disk')),
            ],
        ),
        migrations.CreateModel(
            name='TruckTireCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_images', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.disk')),
            ],
        ),
    ]
