# Generated by Django 5.1.2 on 2024-11-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_company_protector_and_more'),
        ('suppliers', '0005_mototire_find_images_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mototirecompany',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='specialtirecompany',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='truckdiskcompany',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='trucktirecompany',
            name='disk',
        ),
        migrations.AddField(
            model_name='mototirecompany',
            name='mototire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.mototire'),
        ),
        migrations.AddField(
            model_name='specialtirecompany',
            name='specialtire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.specialtire'),
        ),
        migrations.AddField(
            model_name='truckdiskcompany',
            name='truckdisk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.truckdisk'),
        ),
        migrations.AddField(
            model_name='trucktirecompany',
            name='trucktire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.trucktire'),
        ),
        migrations.AlterField(
            model_name='diskcompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='diskcompany',
            name='disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.disk'),
        ),
        migrations.AlterField(
            model_name='mototirecompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='specialtirecompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='tirecompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='tirecompany',
            name='tire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.tire'),
        ),
        migrations.AlterField(
            model_name='truckdiskcompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='trucktirecompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
