# Generated by Django 5.1.2 on 2024-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_ad_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price_multiplier',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
