# Generated by Django 5.1.2 on 2024-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_price_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ad_order_avito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description_avito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='price_multiplier_avito',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='promotion_avito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='protector_avito',
            field=models.CharField(blank=True, choices=[('all_season', 'Всесезонный'), ('summer', 'Лето'), ('winter', 'Зима'), ('winter_spikes', 'Зима/Шипы')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tags_avito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
