# Generated by Django 5.1.2 on 2024-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_ad_order_avito_company_description_avito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='format_xlsx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='seller',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telephone_avito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
