# Generated by Django 5.1.2 on 2024-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_brand_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='promo_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='protector_avito',
            field=models.CharField(blank=True, choices=[('all_season', 'Всесезонный'), ('summer', 'Лето'), ('winter', 'Зимние нешипованные'), ('winter_spikes', 'Зимние шипованные')], max_length=20, null=True),
        ),
    ]
