# Generated by Django 5.1.2 on 2024-11-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_promo_photo_alter_company_protector_avito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='protector',
            field=models.CharField(blank=True, choices=[('cancel', 'Не выбрано'), ('all_season', 'Всесезонный'), ('summer', 'Лето'), ('winter', 'Зима'), ('winter_spikes', 'Зима/Шипы')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='protector_avito',
            field=models.CharField(blank=True, choices=[('cancel', 'Не выбрано'), ('all_season', 'Всесезонный'), ('summer', 'Лето'), ('winter', 'Зимние нешипованные'), ('winter_spikes', 'Зимние шипованные')], max_length=20, null=True),
        ),
    ]
