# Generated by Django 5.1.2 on 2024-11-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_company_protector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='get_other_photo',
            field=models.BooleanField(default=False),
        ),
    ]
