# Generated by Django 5.1.2 on 2024-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_rename_get_other_photo_company_get_other_photo_avito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brand_exception',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
